Feature Typography
Alexey-Samoylo/Test-Task-1 pull request #3
Opened 2023-10-17 12:08 UTC by Alexey-Samoylo

2023-10-17 12:24 UTC, antonsviarzhynski requested changes

2023-10-17 12:35 UTC, Alexey-Samoylo commented on src/elements/typography.tsx
> +            onClick={onClick}>
Corrected.

2023-10-17 12:41 UTC, antonsviarzhynski requested changes

2023-10-18 08:01 UTC, antonsviarzhynski approved these changes

2023-10-18 08:01 UTC, merged